# Generated by Django 3.1.6 on 2021-02-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memeCaption', models.TextField(blank=True)),
                ('memeURL', models.URLField()),
                ('creator', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('lastUpdated', models.DateTimeField()),
                ('likesReceived', models.IntegerField(default=0)),
                ('memeId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='memeId', to='xmeme_backend.meme')),
            ],
        ),
    ]
