# Generated by Django 3.1.6 on 2021-02-05 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 15, 58, 31, 135279)),
        ),
    ]
