# Generated by Django 3.1.6 on 2021-02-05 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0002_meme_creationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 16, 7, 3, 599172, tzinfo=utc)),
        ),
    ]
