# Generated by Django 3.1.6 on 2021-02-05 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0003_auto_20210205_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemeDetails',
            new_name='MemeDetail',
        ),
        migrations.AlterField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 16, 18, 11, 136823, tzinfo=utc)),
        ),
    ]
