# Generated by Django 3.1.6 on 2021-02-05 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0004_auto_20210205_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='memeCaption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='creator',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='memeURL',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 16, 43, 38, 485524, tzinfo=utc)),
        ),
    ]
