# Generated by Django 3.1.6 on 2021-02-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0007_auto_20210207_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='updatedDateTime',
        ),
        migrations.RemoveField(
            model_name='memedetail',
            name='lastUpdated',
        ),
        migrations.AddField(
            model_name='memedetail',
            name='updatedDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='memedetail',
            name='creationDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
