# Generated by Django 3.1.6 on 2021-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0008_auto_20210207_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='memedetail',
            name='creationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
