# Generated by Django 3.1.6 on 2021-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0009_auto_20210207_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='creationDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
