# Generated by Django 3.1.6 on 2021-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0012_auto_20210208_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
