# Generated by Django 3.1.6 on 2021-02-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0014_auto_20210208_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemeDetail',
        ),
    ]
