# Generated by Django 3.1.6 on 2021-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0015_delete_memedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.TextField(max_length=200),
        ),
    ]
