# Generated by Django 3.1.6 on 2021-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme_backend', '0016_auto_20210213_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.URLField(),
        ),
    ]
